### ISSUE TITLE
[-] An error occurred: 'ColorScript' object has no attribute 'parse_input'!

### ISSUE THREAD

**Issue by MeanMachine123** [EntySec/HatSploit#107]
[i] --( The HatSploit Terms of Service )--
This tool is designed for educational purposes only.

Adequate defenses can only be built by researching attack techniques available to malicious actors.
Using this tool against target systems without prior permission is illegal in most jurisdictions.
The authors are not liable for any damages from misuse of this information or code.

If you are planning on using this tool for malicious purposes that are not authorized by the company
you are performing assessments for, you are violating the terms of service and license. 

By accepting our terms of service, you agree that you will only use this tool for lawful purposes only.

[-] An error occurred: 'ColorScript' object has no attribute 'parse_input'!
  File "/usr/local/bin/hsf", line 33, in <module>
    sys.exit(load_entry_point('hatsploit==5.0.0', 'console_scripts', 'hsf')())
  File "/usr/local/lib/python3.11/dist-packages/hatsploit/__init__.py", line 43, in hsf_cli
    runtime.catch(hsf.cli)
  File "/usr/local/lib/python3.11/dist-packages/hatsploit/lib/runtime.py", line 126, in catch
    traceback.print_stack(file=sys.stdout)

**Comment by enty8080** [comment]
Update HatSploit:

```
pip3 install --force-reinstall git+https://github.com/EntySec/HatSploit
```

**Comment by MeanMachine123** [comment]
sudo hsf   
[i] --( The HatSploit Terms of Service )--
This tool is designed for educational purposes only.

Adequate defenses can only be built by researching attack techniques available to malicious actors.
Using this tool against target systems without prior permission is illegal in most jurisdictions.
The authors are not liable for any damages from misuse of this information or code.

If you are planning on using this tool for malicious purposes that are not authorized by the company
you are performing assessments for, you are violating the terms of service and license. 

By accepting our terms of service, you agree that you will only use this tool for lawful purposes only.

[-] An error occurred: 'ColorScript' object has no attribute 'parse_input'!
  File "/usr/local/bin/hsf", line 33, in <module>
    sys.exit(load_entry_point('hatsploit==5.0.0', 'console_scripts', 'hsf')())
  File "/usr/local/lib/python3.11/dist-packages/hatsploit/__init__.py", line 43, in hsf_cli
    runtime.catch(hsf.cli)
  File "/usr/local/lib/python3.11/dist-packages/hatsploit/lib/runtime.py", line 126, in catch
    traceback.print_stack(file=sys.stdout)

Giving same error again.........

**Comment by enty8080** [comment]
@MeanMachine123 Are you sure that HatSploit was installed by pip for your current python version. Please check the version of pip and python. The command above should reinstall all the dependencies.

**Comment by MeanMachine123** [comment]
All other tools are working finely. Pip & python is giving no other error

**Comment by enty8080** [comment]
@MeanMachine123 What python version your pip is configured for?

**Comment by MeanMachine123** [comment]
Issue has been resolved but without sudo support

**Comment by MeanMachine123** [comment]
Colorscript have rights issue
