### ISSUE TITLE
Search Command Bug

### ISSUE THREAD

**Issue by thecakeisfalse** [EntySec/HatSploit#47]
Can you write error in search if user haven't agreed to build database?

Current message:
```
(hsf)> search test
[-] An error occurred: 'NoneType' object has no attribute 'keys'!
(hsf)> 
```

**Comment by enty8080** [comment]
Hello, @thecakeisfalse 

I am glad you interested in my work and project.
Thanks for reporting this bug, I'll fix it.

Regards,
Ivan Nikolsky (@enty8080)

**Comment by enty8080** [comment]
@thecakeisfalse Bug fixed.
