### ISSUE TITLE
History Command Bug

### ISSUE THREAD

**Issue by thecakeisfalse** [EntySec/HatSploit#48]
@enty8080 

When I run ```history -l``` command, it print same text twice.

```bash
(hsf)> history -c
(hsf)> load cowsay
[*] Loading cowsay plugin...
 ________________
< Cow here, moo! >
 ----------------
         \   ^__^ 
          \  (oo)\_______
             (__)\       )\/\
                 ||----w |
                 ||     ||
        
[i] Use cowsay to call me.
[+] Successfully loaded cowsay plugin!
(hsf)> history -l
[i] HatSploit history:
    * load cowsay
    * load cowsay
(hsf)> 
```

**Comment by enty8080** [comment]
Hello, @thecakeisfalse 

I am glad you interested in my work and project.
Thanks for reporting this bug, I'll fix it.

Regards,
Ivan Nikolsky (@enty8080)

**Comment by enty8080** [comment]
@thecakeisfalse, duplicated history commands caused because of adding one scope to another (LocalStorage and GlobalStorage), so it will take some time to fix this.

**P.S** You can now just ignore this problem.

**Comment by enty8080** [comment]
@thecakeisfalse Bug fixed.
