### ISSUE TITLE
Idea for install hatvenom on system.

### ISSUE THREAD

**Issue by dmknght** [EntySec/HatSploit#53]
So from the last issue i created, the HatSploit force install HatVenom from internet automatically. I have and alternative idea. We can try something like `try import hatvenom; except ImportError: <do install from pip>`. IDK if it is possible in `setup.py`. What do you think about it? The idea is to check if system has HatVenom. With this method, `setup.py` can check version of HatVenom as well like
```
try:
  import hatvenom
  if hatvenom.version < "required version":
    print("You are having old version of hatvenom")
    do_upgrade_hatvenom()
  else:
    pass
except ImportError:
   do_install_hatvenom()
```

**Comment by enty8080** [comment]
@enty8080 HatVenom should be installed automatically from setup.py, so it does now matter which version it has, HatSploit does not require HatVenom to be `> 1.0.0`. I think this piece of code is not usable in HatSploit.
