### ISSUE TITLE
Unknown Python Error/Bug

### ISSUE THREAD

**Issue by G00Dway** [EntySec/HatSploit#95]
I dont know, The older versions worked cheap for me but this one gave me error like: 'Casting' object has no attribute 'is_ipv4_range'. Did you mean: 'is_port_range'
I type "hsf" in terminal but it gaves me this error and exits

So, please fix this i really like the framework design/modules/etc..

Thanks!

**Comment by enty8080** [comment]
@G00Dway Hi, try doing this:

```
pip3 uninstall pex
pip3 install git+https://github.com/EntySec/Pex
```

This should help.
