### ISSUE TITLE
Cant Upgrade or Install

### ISSUE THREAD

**Issue by G00Dway** [EntySec/HatSploit#97]
Yo!... yea again me, i wanna say i cant upgrade the framework or even install it after uninstalling

so the problem is the git says theres no github link for HatLoads module!

**Comment by enty8080** [comment]
@G00Dway Try doing this:

```
pip3 uninstall hatsploit
rm -rf ~/.hsf
pip3 install git+https://github.com/EntySec/HatSploit
```

I have removed HatLoads, so it should not install it. So, make sure you are cloning the original version.
